version: '3'
services:
  nginx:
    image: nginx:1.23.1
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    profiles: ['nginx']
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=240h
      - --storage.tsdb.retention.size=4GB
    ports:
      - 9090:9090
    profiles: ['prometheus']
    depends_on:
      - node-exporter
      - nginx-exporter
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    profiles: ['node-exporter']
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    ports:
      - 9113:9113
    command:
      - --nginx.scrape-uri=http://nginx:80/status
      - --web.telemetry-path=/metrics
    profiles: ['nginx-exporter']
    depends_on:
      - nginx
volumes:
  prometheus_data: