global:
  scrape_interval:     20s
  evaluation_interval: 20s

rule_files:
  - /etc/prometheus/alertmanager/rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: nginx-exporter
    static_configs:
      - targets: ['nginx-exporter:9113']