global:
  scrape_interval:     20s
  evaluation_interval: 20s

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: nginx
    static_configs:
      - targets: ['nginx-exporter:9113']