version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    profiles: ['grafana']
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    profiles: ['node-exporter']
volumes:
  grafana_data: