.PHONY: grafana
grafana:
	COMPOSE_PROFILE=grafana docker-compose up

.PHONY: grafana-stop
grafana-stop:
	COMPOSE_PROFILE=grafana docker-compose stop

.PHONY: node-exporter
node-exporter:
	COMPOSE_PROFILE=node-exporter docker-compose  up

.PHONY: node-exporter-stop
node-exporter-stop:
	COMPOSE_PROFILE=node-exporter docker-compose stop