.PHONY: grafana
grafana:
	docker-compose --profile grafana up

.PHONY: grafana-stop
grafana-stop:
	docker-compose --profile grafana stop

.PHONY: node-exporter
node-exporter:
	docker-compose --profile node-exporter up

.PHONY: node-exporter-stop
node-exporter-stop:
	docker-compose --profile node-exporter stop